[package]
name = "uiio"
repository = "https://github.com/runtime-blocks/uiio"
version = "0.0.4"
license = "MIT"
edition = "2021"

[dependencies]
nom = "7.1.3"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.9"
