[package]
name = "uiio"
description = "UI IO for the HUG tool"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
nom = "7.1.3"
thiserror.workspace = true
