[package]
name = "uiio-element"
description = "UI IO essential elements"
repository.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
uiio.workspace = true

[dev-dependencies]
anyhow.workspace = true
